### ISSUE TITLE
Add Screenshots to Readme

### ISSUE THREAD

**Issue by anshumansinha18** [anushruti11/Calculator-app#1]

**Comment by Sockalingam29** [comment]
I would like to work on this. Could you assign me?

**Comment by prahuljose** [comment]
@anushruti11 I'll be happy to help with this for you! Awesome work on the website btw :)
Assign it to me so I can start working on it.

**Comment by anushruti11** [comment]
@Sockalingam29 @prahuljose Let it be assigned to the one who created it. You can create your own!

**Comment by Sockalingam29** [comment]
Oh! I didn't see that you assigned it. What should I do now?
